[package]
name = "whacka-molee"
version = "0.0.1"
edition = "2024"

[dependencies]
box2d-rs = "0.0.4"
earcut = "0.4.4"
fastnoise-lite = "1.1.1"
fluent = "0.16.1"
image = "0.25"
itertools = "0.14.0"
macroquad = "0.4.14"
rand = "0.9.1"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
unic-langid = "0.9.6"
visioncortex = "0.8.8"
vtracer = "0.6"
